import Footer from "@/components/Footer";
import Header from "@/components/Header";
import DeviceProvider from "@/providers/DeviceProvider";

export const metadata = {
  title: "Admin",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DeviceProvider>
          <Header />
          {children}
          <Footer />
        </DeviceProvider>
      </body>
    </html>
  );
}
